{"uuid": "527de9ac-f358-4523-a3a7-24e1aac45924", "children": ["fd70fe69-a618-4b47-87b0-47973343b38f"], "befores": [{"name": "_unittest_setUpClass_fixture_Test_Orange_HRM", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=137.0.7151.104)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6389efea5+79173]\n\tGetHandleVerifier [0x0x7ff6389eff00+79264]\n\t(No symbol) [0x0x7ff6387a9e5a]\n\t(No symbol) [0x0x7ff638796630]\n\t(No symbol) [0x0x7ff638794d50]\n\t(No symbol) [0x0x7ff6387955ff]\n\t(No symbol) [0x0x7ff6387c0cdb]\n\t(No symbol) [0x0x7ff6387b4330]\n\t(No symbol) [0x0x7ff6387b41d2]\n\t(No symbol) [0x0x7ff638785d7a]\n\t(No symbol) [0x0x7ff638783d23]\n\t(No symbol) [0x0x7ff6388692b1]\n\t(No symbol) [0x0x7ff63882896a]\n\t(No symbol) [0x0x7ff63885100d]\n\t(No symbol) [0x0x7ff638828743]\n\t(No symbol) [0x0x7ff6387f14c1]\n\t(No symbol) [0x0x7ff6387f2253]\n\tGetHandleVerifier [0x0x7ff638cba2dd+3004797]\n\tGetHandleVerifier [0x0x7ff638cb472d+2981325]\n\tGetHandleVerifier [0x0x7ff638cd3380+3107360]\n\tGetHandleVerifier [0x0x7ff638a0aa2e+188622]\n\tGetHandleVerifier [0x0x7ff638a122bf+219487]\n\tGetHandleVerifier [0x0x7ff6389f8df4+115860]\n\tGetHandleVerifier [0x0x7ff6389f8fa9+116297]\n\tGetHandleVerifier [0x0x7ff6389df558+11256]\n\tBaseThreadInitThunk [0x0x7ffe3f207034+20]\n\tRtlUserThreadStart [0x0x7ffe3faa26a1+33]\n\n", "trace": "  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\_pytest\\unittest.py\", line 145, in unittest_setup_class_fixture\n    setup()\n    ~~~~~^^\n  File \"D:\\test\\Python_test\\py_test_4\\TestWebUI\\test_WebUI.py\", line 15, in setUpClass\n    cls.driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 638, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\test\\Python_test\\py_test_4\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750175878593, "stop": 1750175883080}], "start": 1750175878593, "stop": 1750175883329}